options:
  cluster_name:
    type: string
    default: cluster1
    description: >-
      'Name to be recorded in database for jobs from this cluster.
      This is important if a single database is used to record
      information from multiple Slurm-managed clusters.'
  custom_config:
    type: string
    default: ""
    description: >-
      'User supplied slurm configuration'
  proctrack_type:
    type: string
    default: proctrack/cgroup
    description: >-
      'Identifies the plugin to be used for process tracking on a job
      step basis.  Can also be set to: proctrack/linuxproc (not
      recommended; might lead to orphan processes).'
  node_weight_criteria:
    type: string
    default: none
    description: >-
      'What type of node criteria to use for setting weights on nodes.
      By default all nodes have Weight=1. When it is preferable to
      allocate for example smaller memory nodes for smaller jobs, low
      weights should be assigned to smaller nodes. Setting this charm
      option will automatically order and weigh the nodes in ascending
      order. Allowed values are RealMemory, CPUs and CoresPerSocket.'
  cgroup_config:
    type: string
    default: |
      CgroupAutomount=yes
      ConstrainCores=yes
    description: >-
      'Configuration content for cgroup.conf'
  log_level:
    type: string
    default: info
    description: |
      The level of detail to provide slurmd daemon's logs. The
      default value is info. Valid choices are: quiet (log nothing),
      fatal (log only fatal errors), info (log errors and general
      information messages), verbose (log errors and verbose
      informational messages). Then there are five debug levels which
      will be increasingly noisy (errors + noise): debug, debug1,
      debug2, debug3, debug4, debug5.
